### ISSUE TITLE
Mode switching and warping.

### ISSUE THREAD

**Issue by bopan3** [ZHU-Zhiyu/NVS_Solver#3]
Hi,
Nice work! I wonder how to swtich between the DGS mode and Post mode? Moreover, I wonder how to let warping code work for zooming out? When I try to zoom out the camera with current warping code, there are obvious aritfacts caused by inccorect zoom out.

<img width="893" alt="截屏2024-06-11 09 46 05" src="https://github.com/ZHU-Zhiyu/NVS_Solver/assets/21981916/7df306d0-2139-42ba-bca2-a49e1e056f17">

**Comment by ZHU-Zhiyu** [comment]
Hi, @bopan3 , the current version only contains NVS-Solver (Post). We will release the NVS-Solver (DGS) in the next few days. For the arbitrary camera trajectory as zoomed out, we are also preparing the code. (Actually, due to the large downsampling ratio of VAE, a straightforward solution is to apply more erosion to the warped image.) We appreciate your patience.

**Comment by mengyou2** [comment]
Hi, I've identified the cause of the artifacts during zoom out. The issue was due to a depth normalization step using $depth = depth - depth.min()$ before warping. Removing this step eliminates the artifacts. I've uploaded the new version, and you can try zooming out now.

**Comment by bopan3** [comment]
That's great!
